In [1]:
import pandas as pd

In [27]:
dataset = pd.read_csv(r'C:\Users\hp\Desktop\14 Days 14 Models\New\car_price_dataset.csv')

In [28]:
dataset.head(4)

,Car_ID,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,Ford,2023,1.2,Hybrid,Manual,180635,4,3,82,34309.25
1,2,Hyundai,2018,3.2,Electric,Manual,35628,2,4,259,55153.60
2,3,BMW,2008,2.2,Diesel,Manual,74672,3,2,333,41894.40
3,4,Hyundai,2017,2.2,Petrol,Automatic,51246,4,4,381,54046.70

In [29]:
dataset.isnull().sum().sum()

np.int64(0)

In [26]:
dataset.drop(columns=["Car_ID"], inplace=True)

In [30]:
for col in dataset.columns:
    print(f"{col}, the dtype is {dataset[col].dtype}")

Car_ID, the dtype is int64
Brand, the dtype is object
Model_Year, the dtype is int64
Engine_Size, the dtype is float64
Fuel_Type, the dtype is object
Transmission, the dtype is object
Mileage, the dtype is int64
Doors, the dtype is int64
Owner_Count, the dtype is int64
Horsepower, the dtype is int64
Price, the dtype is float64

In [17]:
numeric_cols = []
cat_col = []

for col in dataset.columns:
    if dataset[col].dtype != "object" and "category":
        numeric_cols.append(col)
    else:
        cat_col.append(col)
    # print(col)

In [20]:
dataset

,Brand,Model_Year,Engine_Size,Fuel_Type,Transmission,Mileage,Doors,Owner_Count,Horsepower,Price
0,1,2023,1.2,2,1,180635,4,3,82,34309.25
1,3,2018,3.2,1,1,35628,2,4,259,55153.60
2,0,2008,2.2,0,1,74672,3,2,333,41894.40
3,3,2017,2.2,3,0,51246,4,4,381,54046.70
4,3,2012,2.4,1,1,147233,3,4,290,38010.35
...,...,...,...,...,...,...,...,...,...,...
1995,3,2023,4.5,0,1,155033,2,3,310,61734.35
1996,5,2023,1.4,3,1,25044,2,4,271,48467.80
1997,3,2022,4.1,0,1,104372,4,3,191,55714.40
1998,0,2020,4.4,0,0,158047,4,1,186,53222.65
1999,2,2012,1.7,1,0,19706,3,1,165,40687.70

In [18]:
cat_col

[]